# Generated by Django 5.2.3 on 2025-06-13 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('matricula', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Matrícula')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome Completo')),
                ('lotacao', models.CharField(blank=True, max_length=100, null=True, verbose_name='Lotação')),
                ('gerencia_assessoria', models.CharField(blank=True, max_length=100, null=True, verbose_name='Gerência/Assessoria')),
                ('diretoria', models.CharField(blank=True, max_length=100, null=True, verbose_name='Diretoria')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='E-mail')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
                'db_table': 'employees',
            },
        ),
        migrations.CreateModel(
            name='SetorRequisitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_setor', models.CharField(max_length=150, unique=True, verbose_name='Nome do Setor')),
                ('codigo_setor', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Código do Setor')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('responsavel_setor', models.ForeignKey(blank=True, db_column='id_responsavel_setor', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.employee')),
            ],
            options={
                'verbose_name': 'Setor Requisitante',
                'verbose_name_plural': 'Setores Requisitantes',
                'db_table': 'setoresrequisitantes',
            },
        ),
    ]
