# Generated by Django 5.2.3 on 2025-07-29 22:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_centrocusto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Almoxarifado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Almoxarifado')),
                ('codigo', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Código')),
                ('localizacao', models.TextField(blank=True, null=True, verbose_name='Localização/Descrição')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Almoxarifado',
                'verbose_name_plural': 'Almoxarifados',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Categoria')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Categoria de Produto',
                'verbose_name_plural': 'Categorias de Produtos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_produto', models.CharField(max_length=50, unique=True, verbose_name='Código do Produto')),
                ('nome_produto', models.CharField(max_length=255, verbose_name='Nome do Produto')),
                ('descricao_detalhada', models.TextField(blank=True, null=True, verbose_name='Descrição Detalhada')),
                ('unidade_medida', models.CharField(max_length=20, verbose_name='Unidade de Medida')),
                ('estoque_minimo', models.PositiveIntegerField(default=0, verbose_name='Estoque Mínimo')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Cadastro')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='materiais.categoria', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['nome_produto'],
            },
        ),
        migrations.CreateModel(
            name='MovimentoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(help_text='Para SAÍDAS, insira um valor positivo. O sistema o tornará negativo.')),
                ('valor_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída')], max_length=7)),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data do Movimento')),
                ('observacao', models.TextField(blank=True, help_text='Ex: NF 1234, Requisição, Carga Inicial etc.', null=True)),
                ('almoxarifado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentos', to='materiais.almoxarifado')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário Responsável')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentos', to='materiais.produto')),
            ],
            options={
                'verbose_name': 'Movimento de Estoque',
                'verbose_name_plural': 'Movimentos de Estoque',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='Requisicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ABERTO', 'Em Aberto'), ('FINALIZADA', 'Finalizada'), ('ATENDIDA', 'Atendida'), ('CANCELADA', 'Cancelada')], default='ABERTO', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_finalizacao', models.DateTimeField(blank=True, null=True)),
                ('data_estorno', models.DateTimeField(blank=True, null=True, verbose_name='Data do Estorno')),
                ('motivo_estorno', models.TextField(blank=True, null=True, verbose_name='Motivo do Estorno')),
                ('data_atendimento', models.DateTimeField(blank=True, null=True, verbose_name='Data do Atendimento')),
                ('atendido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requisicoes_atendidas', to=settings.AUTH_USER_MODEL, verbose_name='Atendido por')),
                ('centro_custo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requisicoes', to='core.centrocusto', verbose_name='Centro de Custo')),
                ('estornado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requisicoes_estornadas', to=settings.AUTH_USER_MODEL, verbose_name='Estornado por')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requisicoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Requisição',
                'verbose_name_plural': 'Requisições',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='ItemRequisicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade Solicitada')),
                ('quantidade_atendida', models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantidade Atendida')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materiais.produto')),
                ('requisicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='materiais.requisicao')),
            ],
            options={
                'verbose_name': 'Item de Requisição',
                'verbose_name_plural': 'Itens de Requisição',
                'unique_together': {('requisicao', 'produto')},
            },
        ),
    ]
