# Generated by Django 5.2.3 on 2025-07-30 20:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_lote', models.CharField(blank=True, max_length=100, null=True, verbose_name='Código do Lote/Referência')),
                ('data_validade', models.DateField(verbose_name='Data de Validade')),
                ('quantidade_atual', models.PositiveIntegerField(default=0, verbose_name='Quantidade Atual no Lote')),
                ('data_entrada', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Entrada do Lote')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='materiais.produto')),
            ],
            options={
                'verbose_name': 'Lote de Produto',
                'verbose_name_plural': 'Lotes de Produtos',
                'ordering': ['data_validade'],
                'unique_together': {('produto', 'data_validade')},
            },
        ),
    ]
