# Generated by Django 5.2.3 on 2025-07-30 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0002_lote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentoestoque',
            name='tipo',
            field=models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída'), ('AJUSTE', 'Ajuste')], max_length=7),
        ),
        migrations.DeleteModel(
            name='Lote',
        ),
    ]
