# Generated by Django 5.2.3 on 2025-08-15 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0004_remove_movimentoestoque_produto_lote_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FechamentoMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.PositiveSmallIntegerField(verbose_name='Mês')),
                ('ano', models.PositiveSmallIntegerField(verbose_name='Ano')),
                ('data_fechamento', models.DateTimeField(auto_now_add=True, help_text='Data e hora em que o processo de fechamento foi executado.', verbose_name='Realizado em')),
                ('responsavel', models.ForeignKey(help_text='Usuário que realizou o fechamento.', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Fechamento Mensal',
                'verbose_name_plural': 'Fechamentos Mensais',
                'ordering': ['-ano', '-mes'],
                'unique_together': {('mes', 'ano')},
            },
        ),
        migrations.CreateModel(
            name='PosicaoEstoqueMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_final', models.DecimalField(decimal_places=2, help_text='Saldo do produto no momento exato do fechamento.', max_digits=10, verbose_name='Quantidade Final')),
                ('custo_medio_final', models.DecimalField(decimal_places=2, help_text='Custo médio do produto no momento do fechamento.', max_digits=10, verbose_name='Custo Médio Final')),
                ('valor_total_final', models.DecimalField(decimal_places=2, help_text='Valor total em estoque (Quantidade * Custo Médio).', max_digits=12, verbose_name='Valor Total Final (R$)')),
                ('fechamento', models.ForeignKey(help_text='O fechamento ao qual esta fotografia de estoque pertence.', on_delete=django.db.models.deletion.CASCADE, related_name='posicoes', to='materiais.fechamentomensal')),
                ('produto', models.ForeignKey(help_text='O produto que está sendo registrado.', on_delete=django.db.models.deletion.PROTECT, to='materiais.produto')),
            ],
            options={
                'verbose_name': 'Posição de Estoque Mensal',
                'verbose_name_plural': 'Posições de Estoque Mensais',
                'unique_together': {('fechamento', 'produto')},
            },
        ),
    ]
