# Generated by Django 5.2.3 on 2025-08-15 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0005_fechamentomensal_posicaoestoquemensal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fechamentomensal',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='fechamentomensal',
            name='cancelado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fechamentos_cancelados', to=settings.AUTH_USER_MODEL, verbose_name='Cancelado por'),
        ),
        migrations.AddField(
            model_name='fechamentomensal',
            name='data_cancelamento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data do Cancelamento'),
        ),
        migrations.AddField(
            model_name='fechamentomensal',
            name='status',
            field=models.CharField(choices=[('ATIVO', 'Ativo'), ('CANCELADO', 'Cancelado')], default='ATIVO', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='fechamentomensal',
            name='data_fechamento',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Realizado em'),
        ),
        migrations.AlterField(
            model_name='fechamentomensal',
            name='responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Responsável'),
        ),
        migrations.AlterUniqueTogether(
            name='fechamentomensal',
            unique_together={('mes', 'ano', 'status')},
        ),
    ]
