# Generated by Django 5.2.3 on 2025-08-18 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0006_alter_fechamentomensal_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código da classe do produto.', max_length=20, unique=True)),
                ('descricao', models.TextField(verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Classe',
                'verbose_name_plural': 'Classes',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='NaturezaDespesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código da Natureza de Despesa.', max_length=20, unique=True)),
                ('descricao', models.TextField(verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Natureza de Despesa',
                'verbose_name_plural': 'Naturezas de Despesa',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='PDM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código do PDM.', max_length=20, unique=True)),
                ('descricao', models.TextField(verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'PDM',
                'verbose_name_plural': 'PDMs',
                'ordering': ['codigo'],
            },
        ),
        migrations.AddField(
            model_name='produto',
            name='classe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='materiais.classe', verbose_name='Classe'),
        ),
        migrations.AddField(
            model_name='produto',
            name='natureza_despesa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='materiais.naturezadespesa', verbose_name='Natureza da Despesa'),
        ),
        migrations.AddField(
            model_name='produto',
            name='pdm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='materiais.pdm', verbose_name='PDM'),
        ),
    ]
